Wiki: Fix documentation not using pax word as in game
IDI-Systems/acre2 pull request #1037
Opened 2020-11-09 17:52 UTC by Vdauphin

**When merged this pull request will:**
- This PR switch from "passenger" to "pax" as it is used in game.

2020-11-09 18:15 UTC, TheMagnetar requested changes
Too much mass replace :D

2020-11-09 18:15 UTC, TheMagnetar commented on docs/wiki/user/vehicle-intercom.md
> +Vehicle intercom consists of two separate networks depending on the vehicle type: crew and pax intercom. Intercom gives the ability to speak to other players within the same network using a headset.
```suggestion
Vehicle intercom consists of two separate networks depending on the vehicle type: crew and passenger (pax) intercom. Intercom gives the ability to speak to other players within the same network using a headset. This allows them to communicate without the disturbance of the vehicle's noise.
```

2020-11-09 18:15 UTC, TheMagnetar commented on docs/wiki/user/vehicle-intercom.md
> +While *crew intercom* is limited to crew members and players in cargo positions cannot have access to it, *pax intercom* can be accessed by both crew and pax. This allows the crew to communicate with
```suggestion
While *crew intercom* is limited to crew members and players in cargo positions cannot have access to it, *pax intercom* can be accessed by both crew and passengers. This allows the crew to communicate with the passengers if such network exist. In order to connect to the *pax intercom*, ACE3 Interaction Menu is needed: simply interact with the vehicle when being in a seat with access to *pax intercom* and select connect. *Crew intercom* is automatically assigned to players in "crew" positions.
```

2020-11-09 18:15 UTC, TheMagnetar commented on docs/wiki/user/vehicle-intercom.md
> +Infantry also has the possibility, in vehicles like tanks or IFVs, to communicate with the crew and/or pax without entering the vehicle. To do so, face the vehicle, interact with it and take the infa
```suggestion
Infantry also has the possibility, in vehicles like tanks or IFVs, to communicate with the crew and/or passengers without entering the vehicle. To do so, face the vehicle, interact with it and take the infantry telephone by selecting the appropriate network if it is not in use already. You can either put it back, give it to another player or switch networks.
```

2020-11-09 18:15 UTC, TheMagnetar commented on docs/wiki/user/vehicle-intercom.md
> +Crew members (not pax) can make the infantry telephone ring as long as it is not in use. In order to do so, interact with the vehicle from one of the allowed positions (driver, commander, gunner and
```suggestion
Crew members (not passengers) can make the infantry telephone ring as long as it is not in use. In order to do so, interact with the vehicle from one of the allowed positions (driver, commander, gunner and turret positions) and select start/stop ringing. The ringing will automatically stop once the infantry telephone is picked up, the vehicle is destroyed or no crew members are aboard.
```

2020-11-09 18:43 UTC, Vdauphin commented
Perfect now :)

2020-11-18 09:42 UTC, jonpas approved these changes

2020-11-18 12:46 UTC, TheMagnetar approved these changes

2020-11-18 13:15 UTC, merged