Documentation -- Function Headers -- sys_prc77
IDI-Systems/acre2 pull request #109
Opened 2016-11-29 13:14 UTC by TheMagnetar

**When merged this pull request will:**
- Handle documentation issue #107: sys_prc77 component. WIP.

2017-02-16 15:47 UTC, jonpas requested changes
No semi-colons in header examples.

2017-04-08 21:49 UTC, jonpas requested changes

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/functions/fnc_onFunctionKnobPress.sqf
> + * squelch (2), retrans (3) and lite (4).
All 5 modes on same line is cleaner to read.

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/functions/fnc_onPresetKnobPress.sqf
> +    //Select array according to preset handler (left,right) [x,y]
Spaces after `//` here too.

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/radio/fnc_getExternalAudioPosition.sqf
> + * array of zeros and does nothing.
`zeroes`

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/radio/fnc_getListInfo.sqf
> + * For a AN/PRC 77 this function is the same as acre_sys_prc77_getChannelDescription,
`same as FUNC(getChannelDescription)` or just `same as getChannelDescription`.

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/radio/fnc_getState.sqf
> + * Function to obtain the content of the radio data hash for the event data key
Missing final dot.

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/radio/fnc_handleBeginTransmission.sqf
>  true;
Should have no semi-colon.

2017-04-08 21:49 UTC, jonpas commented on addons/sys_prc77/radio/fnc_openGui.sqf
> + *
One line less.

2017-04-08 21:54 UTC, TheMagnetar commented on addons/sys_prc77/radio/fnc_getExternalAudioPosition.sqf
> + * array of zeros and does nothing.
Array of zeros is correct.

2017-04-08 21:59 UTC, jonpas commented on addons/sys_prc77/radio/fnc_getExternalAudioPosition.sqf
> + * array of zeros and does nothing.
Apparently both are, urgh.

2017-04-08 22:02 UTC, jonpas approved these changes

2017-04-08 22:15 UTC, merged