Documentation -- Function Headers -- sys_prc343
IDI-Systems/acre2 pull request #110
Opened 2016-11-29 13:15 UTC by TheMagnetar

**When merged this pull request will:**
- Handle documentation issue #107: sys_prc343 component. WIP.

2017-02-16 15:47 UTC, jonpas requested changes
No semi-colons in header examples.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_closeGui.sqf
> + * true <BOOL>
`True <BOOL>`

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getCurrentChannel.sqf
> + * Current channel id <NUMBER>
`ID`

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getCurrentChannel.sqf
> + * 1: Event (Unused) <STRING>
`<STRING> (Unused)` move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getCurrentChannel.sqf
> + * 2: Event data (Unused) <NUMBER>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getChannelData.sqf
> + * 0: Radio ID (Unused) <STRING>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getChannelData.sqf
> + * 1: Event with the value "getChannelData" (Unused) <STRING>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getCurrentChannel.sqf
> + * 0: Radio ID <STRING>
Also unused.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getChannelDescription.sqf
> + * 0: Radio ID <STRING>
Add the unused ones.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_closeGui.sqf
> + * 1: Event with the value "getChannelData" (Unused) <STRING>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_closeGui.sqf
> + * 2: Event data with the channel number (Unused) <NUMBER>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_closeGui.sqf
> + * 3: Radio data (Unused) <HASH>
Move unused to end.

2017-02-16 15:47 UTC, jonpas commented on addons/sys_prc343/radio/fnc_closeGui.sqf
> + * Close radio GUI when calling this function. Event rised by onUnload (PRC343_RadioDialog).
`raised`, no `when calling this function`, that's rather obvious.

2017-02-16 17:16 UTC, TheMagnetar commented
Sorry I should have uploaded the changes.

2017-02-27 16:29 UTC, jonpas requested changes

2017-02-27 16:29 UTC, jonpas commented on addons/sys_prc343/functions/fnc_onChannelKnobPress.sqf
> + * [ARGUMENTS] call acre_sys_prc343_fnc_onChannelKnobPress;
Still no semi-colons. :)

2017-03-01 22:30 UTC, jonpas requested changes

2017-03-01 22:30 UTC, jonpas commented on addons/sys_prc343/functions/fnc_render.sqf
> + * Renders the radio when opened
Missing final dot.

2017-03-01 22:30 UTC, jonpas commented on addons/sys_prc343/functions/fnc_render.sqf
> + * [DisplazID] call acre_sys_prc343_fnc_render
Y instead of Z.

2017-03-01 22:30 UTC, jonpas commented on addons/sys_prc343/functions/fnc_zoomChannelBlockSelector.sqf
> + * 0: Zoom in(0) or out (1) <BOOL>
Space after `in`.

2017-03-01 22:30 UTC, jonpas commented on addons/sys_prc343/radio/fnc_getCurrentChannelInternal.sqf
> + * Returns the unique identity of the current channel since the PRC343 has multiple blocks
Missing final dot.

2017-03-02 07:08 UTC, TheMagnetar commented
I will test it later in the day since this PR also introduces params of the form: `params ["_radioId", "",  "", "", ""];`

2017-03-02 17:29 UTC, TheMagnetar commented
I tested this and it should be ready to be merged.

2017-03-02 17:34 UTC, jonpas approved these changes

2017-03-02 17:34 UTC, merged