SQFC support
IDI-Systems/acre2 pull request #1106
Opened 2021-05-20 20:04 UTC by PabstMirror

Will need to update acre2_tools.zip

2021-05-20 23:17 UTC, PabstMirror commented
- [ ]  Look into using https://github.com/arma-actions/sqfc/ (it's exe is out of date right now)

2021-07-13 13:00 UTC, jonpas requested changes

2021-07-13 13:00 UTC, jonpas commented on addons/main/script_macros.hpp
> +#endif
Guess this can be removed now.
```suggestion
```

2021-07-13 13:00 UTC, jonpas commented on hemtt.toml
> +    "echo 'compile_sqf'",
```suggestion
    "echo Compile SQF",
```

2021-07-13 13:00 UTC, jonpas commented on hemtt.toml
> +    "py tools/compile_sqf.py cleanup build"
```suggestion
    "python tools/compile_sqf.py cleanup build"
```

2021-07-13 13:00 UTC, jonpas commented on hemtt.toml
> +    "py tools/compile_sqf.py cleanup"
```suggestion
    "python tools/compile_sqf.py cleanup"
```

2021-07-13 13:00 UTC, jonpas commented on hemtt.toml
> +    "echo 'compile_sqf_cleanup'",
```suggestion
    "echo Compile SQF Cleanup",
```

2021-07-13 13:00 UTC, jonpas commented on sqfc.json
> +        "P:/idi/acre/addons/"
Release CI has no P-drive.

2021-07-26 05:56 UTC, PabstMirror commented on sqfc.json
> +        "P:/idi/acre/addons/"
updated release.yml to map one

2021-07-27 07:33 UTC, jonpas commented on sqfc.json
> +        "P:/idi/acre/addons/"
Nice

2021-08-11 10:05 UTC, jonpas approved these changes

2021-08-11 10:06 UTC, merged