Documentation -- Function Headers -- sys_signal
IDI-Systems/acre2 pull request #111
Opened 2016-11-29 13:23 UTC by Soldia1138

sys_signal of #107

2016-11-29 13:51 UTC, jonpas approved these changes

2016-11-29 17:32 UTC, Sniperhid requested changes

2016-11-29 17:32 UTC, Sniperhid commented on addons/sys_signal/fnc_handleSignalReturn.sqf
> + * Return function for signal calculation. Will be called after signal has been calculated in extension
in *the* extension

2016-11-29 18:46 UTC, jonpas commented on addons/sys_signal/fnc_getSignal.sqf
> + * [FREQUENCY, POWER, "_radioID1", "_radioID2"] call acre_sys_signal_fnc_getSignal
Preferably those examples should have an example of direct data input.

2016-11-29 22:09 UTC, Soldia1138 commented
Deleted the example and corrected the wording on return Function

2016-11-30 00:07 UTC, Sniperhid approved these changes
LGTM

2016-11-30 15:07 UTC, jonpas requested changes

2016-11-30 15:07 UTC, jonpas commented on addons/sys_signal/fnc_handleSignalReturn.sqf
> + * -
`None`

2016-11-30 15:07 UTC, jonpas commented on addons/sys_signal/fnc_handleSignalReturn.sqf
> + * Return function for signal calculation. Will be called after signal has been calculated in the extension
Should be dot at the end, so it'll look nice when we generate the functions list (this one won't be there, but still, consistency).

2016-11-30 15:07 UTC, jonpas commented on addons/sys_signal/fnc_getSignal.sqf
> + * Wrapper function for calling the signal calculation (extension)
Final dot too.

2016-12-12 06:00 UTC, jonpas approved these changes

2016-12-12 06:03 UTC, merged