Plugin auto-copy overhaul
IDI-Systems/acre2 pull request #114
Opened 2016-11-30 02:33 UTC by Sniperhid

**When merged this pull request will:**
- Removes the config file and instead directly compares the dlls
- Adds Roaming application data folder to scan list - In anticipation of TS 3.1 (Partially addressing #83)
- Skips searching non-existent folders - Should registry/users not be using updated version.

2016-12-08 00:15 UTC, jonpas requested changes
I know it's WIP, but [snake formatting](http://acre2.idi-systems.com/wiki/development/coding-guidelines-cpp#variable-names) as per coding style guidelines.

2016-12-08 00:15 UTC, jonpas commented on extensions/src/ACRE2Steam/CallExt_DllMain.cpp
> +    {
Opening brace on same line as per coding style guidelines.

2017-01-14 15:56 UTC, Sniperhid commented
@jonpas - addressed seeking updated review. Tested this locally myself and seems to work well

2017-01-14 22:11 UTC, jonpas approved these changes

2017-01-14 22:12 UTC, jonpas commented
Looks good code wise, however it's still not using snake formatting (I clicked approve before checking that). I think we should also get rid of the old code.

2017-01-20 13:04 UTC, jonpas approved these changes
Awesome work @Sniperhid !

2017-01-20 15:08 UTC, merged