Add Western Sahara compatibility
IDI-Systems/acre2 pull request #1169
Opened 2021-11-18 14:39 UTC by Dahlgren

**When merged this pull request will:**
- Add support for Western Sahara terrain Sefrou-Ramal

2021-11-18 14:41 UTC, jonpas commented on optionals/sys_ws/config.cpp
> +    class stozec {
This doesn't seem correct.

2021-11-18 15:04 UTC, Dahlgren commented on optionals/sys_ws/config.cpp
> +    class stozec {
Good eyes, fixed!

2021-11-18 15:06 UTC, jonpas approved these changes

2021-11-18 15:36 UTC, BaerMitUmlaut requested changes

2021-11-18 15:36 UTC, BaerMitUmlaut commented on optionals/sys_ws/LICENCE
> +Some items in this component (this folder and all subfolders)
Typo in filename.

2021-11-18 15:37 UTC, jonpas commented on optionals/sys_ws/LICENCE
> +Some items in this component (this folder and all subfolders)
In CSLA too actually, nice catch!

2021-11-20 00:42 UTC, Dahlgren commented on optionals/sys_ws/LICENCE
> +Some items in this component (this folder and all subfolders)
Fixed 🙂

2021-11-22 20:18 UTC, merged