Racks - Fixed issue preventing vehicle racks from using certain intercoms
IDI-Systems/acre2 pull request #1255
Opened 2023-07-02 21:26 UTC by Quantx

This PR fixes a bug where vehicle racks are only able to use the first configured intercom.

This is bug occurs because `acre_sys_intercom_intercomNames` contains a list of intercoms in the following format:
```
[["intercom_1","Crew Intercom","Crew"],["intercom_2","Pax Intercom","Pax"]]
```
However, the following code only checks the first entry in the above list:
```
private _configuredIntercoms = _vehicle getVariable [QEGVAR(sys_intercom,intercomNames), []];
if (_int in (_configuredIntercoms select 0)) then {
```

2023-07-19 13:27 UTC, jonpas requested changes
Let's also fix the return value on L11 to ` * Wired Intercoms <ARRAY>`.

2023-07-19 13:27 UTC, jonpas commented on addons/sys_rack/fnc_configWiredIntercoms.sqf
>              private _int = _x;
```suggestion
```

2023-07-19 13:27 UTC, jonpas commented on addons/sys_rack/fnc_configWiredIntercoms.sqf
>                  WARNING_3("No intercom %1 defined but rack %2 can have access to its network for %3 - skipping",_int,_rack,typeOf _vehicle)
```suggestion
            if (_x in _intercomIds) then {
                _wiredIntercoms pushBack _x;
            } else {
                WARNING_3("No intercom %1 defined but rack %2 can have access to its network for %3 - skipping",_x,_rack,typeOf _vehicle)
```

2023-07-23 21:54 UTC, Quantx commented on addons/sys_rack/fnc_configWiredIntercoms.sqf
>                  WARNING_3("No intercom %1 defined but rack %2 can have access to its network for %3 - skipping",_int,_rack,typeOf _vehicle)
Suggested changes have been made.

2023-07-23 21:54 UTC, Quantx commented on addons/sys_rack/fnc_configWiredIntercoms.sqf
>              private _int = _x;
Suggested changes have been made

2023-08-06 18:14 UTC, jonpas approved these changes

2023-08-06 18:20 UTC, merged