Racks - Fix VRC64 / PRC-77 connector
IDI-Systems/acre2 pull request #1284
Opened 2023-09-17 18:43 UTC by PabstMirror

Calling `[_vehicle] call acre_api_fnc_areVehicleRacksInitialized;` from scheduled will throw
```
 Error in expression < select 1;
if (_parentConnectorType == _childConnectorType) then {
private _exi>
   Error position: <_childConnectorType) then {
private _exi>
  Error Undefined variable in expression: _childconnectortype
 File idi\acre\addons\sys_components\fnc_attachComplexComponent.sqf..., line 45
```
https://github.com/IDI-Systems/acre2/blob/10d20356df3f3b1e74ab910e99a191ebcbfc612a/addons/sys_rack/vrc64/fnc_vrc64MountRadio.sqf#L24
but there isn't a index 2 `connectors[]` on the radio

This adds a new 14 pin connector, I think this was the original intent, but I'm not positive

2023-09-17 21:55 UTC, rautamiekka requested changes

2023-09-17 21:55 UTC, rautamiekka commented on docs/wiki/frameworks/vehicle-racks.md
> +  - `"ACRE_VRC64"`: Can mount a `"ACRE_PRC77"`
```suggestion
  - `"ACRE_VRC64"`: Can mount a `"ACRE_PRC77"`.
```
For consistency with the below lines.

2023-09-25 15:42 UTC, jonpas commented
Also fix VRC-110 power documentation (was stating 50W, is actually 20W) and add VRC-64 to the wiki.

2023-09-25 15:42 UTC, jonpas approved these changes

2023-09-25 18:22 UTC, PabstMirror commented on docs/wiki/user/vehicle-racks.md
> +- **SEM 90**: Allows mounting a *SEM 70*, maintaining its transmitting power at 4W on low poer or increasing it to 40W on high power.
```suggestion
- **SEM 90**: Allows mounting a *SEM 70*, maintaining its transmitting power at 4W on low power or increasing it to 40W on high power.
```

2023-09-25 21:11 UTC, merged