XEH_PreInit (corner cases)
IDI-Systems/acre2 pull request #151
Opened 2016-12-19 13:38 UTC by TheMagnetar

**When merged this pull request will:**
- Move functions defined in main/XEH_preInit.sqf to separate function files.

- [x] EFUNC(lib,getGear) to sys_core/fnc_getGear.sqf
- [x] EFUNC(lib,replaceGear) to sys_core/fnc_replaceGear.sqf
- [x] EFUNC(lib,removeGear) to sys_core/fnc_removeGear.sqf
- [x] EFUNC(lib,addGear) to sys_core/fnc_addGear.sqf
- [ ] EFUNC(lib,getCompartment)
- [ ] EFUNC(lib,fastHashCreate)
- [ ] EFUNC(lib,fastHashCopyArray)
- [ ] EFUNC(lib,fastHashCopy)
- [ ] EFUNC(lib,fastHashKeys)

2016-12-19 17:01 UTC, jonpas requested changes
Some changes needed.

> Should the Hash functions also be moved to sys_core or Should they remain in main?

Should also be moved.

2016-12-19 17:01 UTC, jonpas commented on addons/api/fnc_basicMissionSetup.sqf
> +        [_player, "ItemRadio"] call EFUNC(sys_core, removeGear);
No space between component name and function name.

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_addGear.sqf
> + * 0: unit <OBJECT>
Capitalization, eg. `Unit`, same for the rest.

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_addGear.sqf
> + *    <STRING><OPTIONAL>
On same line and like that: `... <STRING> (default: "")`

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_addGear.sqf
> +if ( _gearContainer != "") then {
Space after opening brace.

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_addGear.sqf
> +params ["_unit", "_item",["_gearContainer",""]];
Missing space after second comma

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_getGear.sqf
> + * Array of ACRE related gear
`ACRE related gear <ARRAY>`

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_replaceGear.sqf
> + * related items
Same line, this even fits GitHub's width. 😆

2016-12-19 17:01 UTC, jonpas commented on addons/sys_core/fnc_addGear.sqf
> + * container (uniform, vest or backpack) or wherever can be added.
Entire sentence on second line would look better IMO.

2016-12-20 13:32 UTC, TheMagnetar commented
Missing functions have been added. This is now complete.

2016-12-20 13:57 UTC, jonpas requested changes
Minor documentation things, good otherwise.

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_fastHashCopy.sqf
> + * 0: ACRE 2 Hash <ARRAY> or object <OBJECT>
`* 0: ACRE 2 Hash <ARRAY>/<OBJECT>`

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_getCompartment.sqf
> + * Relevant for signal attenuating purposes
Missing final point.

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_fastHashKeys.sqf
> + * This function can be accessed through the macro HASH_KEYS
Missing final point.

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_fastHashKeys.sqf
> + * 0: ACRE 2 hash <HASH> or object <OBJECT>
Probably cleaner that way for future automated docs:
`* 0: ACRE 2 Hash <ARRAY>/<OBJECT>`

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_fastHashCopyArray.sqf
> + * [ARGUMENTS] call acre_sys_core_fnc_fastHashCopyArray
Missing `ARGUMENTS` example.

2016-12-20 13:57 UTC, jonpas commented on addons/sys_core/fnc_fastHashCopy.sqf
> + * Copies one hash to another or creates an ACRE2 hash with the object variables if the input is an object
Missing final point

2016-12-20 14:30 UTC, jonpas requested changes

2016-12-20 14:30 UTC, jonpas commented on addons/sys_core/fnc_fastHashCopyArray.sqf
> + * 0: ACRE 2 Hash <HASH>/<ARRAY> to be copied
VIce-versa:
`* 0: ACRE 2 Hash to be copied <HASH>/<ARRAY>`

2016-12-20 14:35 UTC, jonpas approved these changes

2016-12-20 19:38 UTC, Sniperhid approved these changes

2016-12-23 16:40 UTC, Sniperhid requested changes
It seems when I start the game with this PR my game crashes @jonpas - can you reproduce?

2017-01-02 14:37 UTC, Sniperhid approved these changes

2017-01-02 14:37 UTC, Sniperhid commented on addons/main/XEH_preInit.sqf
> +EFUNC(sys_core,fastHashCreate) = {
I'd suggest just adding a comment above this to explain the potential crash if moved.

2017-01-11 17:52 UTC, Sniperhid commented
The current gameplan will be to port all sqf code from `main` to `sys_core`. So this is still WIP till it's completed.

2017-01-25 21:03 UTC, jonpas requested changes

2017-01-25 21:03 UTC, jonpas commented on addons/main/XEH_preInit.sqf
> +  if (count FAST_HASH_POOL > 0) exitWith {
4 spaces indentation.

2017-01-25 21:03 UTC, jonpas commented on addons/main/fnc__garbageCollector.sqf
> + * ACRE 2 garbage collector. Run as a per frame event handler..
One final dot too much.

2017-01-25 21:03 UTC, jonpas commented on addons/main/fnc__hashMonitor.sqf
> + * Handles deletion and creation of acre hashes.
`... ACRE2 hashes.`

2017-01-25 21:03 UTC, jonpas commented on addons/main/XEH_PREP.hpp
> +PREP(_garbageCollector);
Let's just make them without leading underscore.

2017-01-25 21:25 UTC, jonpas approved these changes

2017-01-26 11:28 UTC, merged