Moved functions from sys_gui/fnc_openInventory to separate files
IDI-Systems/acre2 pull request #152
Opened 2016-12-19 14:02 UTC by TheMagnetar

**When merged this pull request will:**

- Move functions defined in sys_gui/fnc_openInventory.sqf to separate function files.

- [x] handleContextMenu
- [x] inventoryMonitorPFH
- [x] onInventoryAction
- [x] uniqueArray

**Of importance** fnc_handleContextMenu does nothing but it is used several times.

2016-12-19 17:08 UTC, jonpas requested changes
I assume headers aren't done yet, so marking WIP.

> **Of importance** fnc_handleContextMenu does nothing but it is used several times.

I must be blind, can you link an example of it's usage? GitHub search `handleContextMenu` doesn't find any.

2016-12-19 17:08 UTC, jonpas commented on addons/sys_gui/script_component.hpp
> +#define IDC_FG_GROUND_ITEMS       632
No multiple spaces, one is fine, there is highlighting for differentiation.

2016-12-19 17:08 UTC, jonpas commented on addons/sys_gui/fnc_onInventoryAction.sqf
> +private _container = nil;
Move below, next to L28?

2016-12-19 17:08 UTC, jonpas commented on addons/sys_gui/fnc_onInventoryAction.sqf
> +_idc = ctrlIDC (_idc);
Useless braces around `(_idc)`.

2016-12-19 17:08 UTC, jonpas commented on addons/sys_gui/fnc_onInventoryAction.sqf
> +    case 'uniform': {
Should use double quotes for consistency.

2016-12-19 17:08 UTC, jonpas commented on addons/sys_gui/fnc_inventoryMonitorPFH.sqf
> +    [(_this select 1)] call CBA_fnc_removePerFrameHandler;
Useless braces around `(_this select 1)`.

2016-12-19 19:43 UTC, TheMagnetar commented
You can find the calls to handleContextMenu in sys_gui/fnc_inventoryMonitorPFH.sqf (originally in fnc_openInventory.sqf)

2016-12-19 22:10 UTC, TheMagnetar commented
Changes done with some additional improvements from your comments.

2016-12-20 14:02 UTC, jonpas requested changes
Some more minor changes needed.

2016-12-20 14:02 UTC, jonpas commented on addons/sys_gui/fnc_handleContextMenu.sqf
> +DFUNC(handleContextMenu) = {
Not necessary to define another function of same name.

2016-12-20 14:02 UTC, jonpas commented on addons/sys_gui/fnc_onInventoryAction.sqf
> + * false <BOOL>
`* False <BOOL>`

2016-12-20 14:02 UTC, jonpas commented on addons/sys_gui/fnc_onInventoryAction.sqf
> + * Checks whther the an ACRE radio is selected or opened in the inventory
Missing final point.

2016-12-20 14:02 UTC, jonpas commented on addons/sys_gui/fnc_uniqueArray.sqf
> + * Returns an array of unique elements without nil values
Missing final point.

2016-12-20 14:02 UTC, jonpas commented on addons/sys_gui/fnc_inventoryMonitorPFH.sqf
> + * ADDPFH(DFUNC(inventoryMonitorPFH), 0, []);
Should probably write it out or something. Like 
`* [acre_sys_gui_inventoryMonitorPFH, 0, []] call CBA_fnc_addPerFrameHandler`
and without final `;`.
Preferably we don't want macros in examples.

2016-12-20 14:36 UTC, jonpas approved these changes

2016-12-20 19:36 UTC, Sniperhid approved these changes

2016-12-23 16:35 UTC, Sniperhid requested changes
Expierenced this during launching the game and opening a mission:
```
16:34:03 Error in expression < call acre_sys_gui_fnc_onInventoryAction)];
((findDisplay 602) displayCtrl 638) >
16:34:03   Error position: <)];
((findDisplay 602) displayCtrl 638) >
16:34:03   Error Missing ;
16:34:03 File idi\acre\addons\sys_gui\fnc_inventoryMonitorPFH.sqf, line 17
```

2016-12-24 18:49 UTC, Sniperhid commented on addons/sys_gui/fnc_inventoryMonitorPFH.sqf
> +    (INVENTORY_DISPLAY displayCtrl IDC_FG_UNIFORM_CONTAINER) ctrlSetEventHandler["LBDblClick", QUOTE([1, "uniform", _this] call FUNC(onInventoryAction))];
`QUOTE([1, "uniform", _this] call FUNC(onInventoryAction))`
->
`QUOTE([1, 'uniform', _this] call FUNC(onInventoryAction))`

`"` is an escape character here.

Do for this for the entire file should fix the error I think!

2016-12-28 13:24 UTC, TheMagnetar commented
Fixed. Anybody understands why changing from
`(INVENTORY_DISPLAY displayCtrl IDC_FG_VEST_CONTAINER) ctrlSetEventHandler ["LBDblClick", QUOTE([1, "vest", _this] call FUNC(onInventoryAction))];` 
to
`(INVENTORY_DISPLAY displayCtrl IDC_FG_UNIFORM_CONTAINER) ctrlSetEventHandler["LBDblClick", "[1, 'uniform', _this] call acre_sys_gui_fnc_onInventoryAction"];`
did the trick despite declaring `onInventoryAction` before `inventoryMonitorPFH` in XEH_PREP.hpp?

2016-12-28 13:30 UTC, jonpas commented on addons/sys_gui/fnc_inventoryMonitorPFH.sqf
> +    (INVENTORY_DISPLAY displayCtrl IDC_FG_UNIFORM_CONTAINER) ctrlSetEventHandler["LBDblClick", "[1, 'uniform', _this] call acre_sys_gui_fnc_onInventoryAction"];         (INVENTORY_DISPLAY displayCtrl
2 code lines on same line.

2016-12-28 13:35 UTC, jonpas commented
> Anybody understands why changing from ... did the trick ...

Yep, 2 things, `QUOTE` just adds `""`, so you still have to use single quotes inside, or quadruple codes (`QUOTE('something')` or `QUOTE(""something"")`).

The second thing is, arrays in `QUOTE `need to be handled separately, due to the preprocessor, using `ARR_N` macros.

The following line should work:
`(INVENTORY_DISPLAY displayCtrl IDC_FG_VEST_CONTAINER) ctrlSetEventHandler ["LBDblClick", QUOTE([ARR_3(1,'vest',_this)] call FUNC(onInventoryAction))];`

2016-12-28 14:56 UTC, Dorbedo commented on addons/sys_gui/fnc_inventoryMonitorPFH.sqf
> +    (INVENTORY_DISPLAY displayCtrl IDC_FG_UNIFORM_CONTAINER) ctrlSetEventHandler["LBDblClick", QUOTE([1, "uniform", _this] call FUNC(onInventoryAction))];
QUOTE([ARR_3(1, 'uniform', _this)] call FUNC(onInventoryAction))
this would be the right usage of the macro

2016-12-29 10:28 UTC, Sniperhid approved these changes

2016-12-29 10:31 UTC, merged