sys_core cleanup - document, cleanup
IDI-Systems/acre2 pull request #171
Opened 2017-01-14 11:38 UTC by Sniperhid

**When merged this pull request will:**
- Document all function headers in sys_core
- Optimize - add lazy eval and remove some unnecessary logic
- Client send teamspeak ID loop - Send an update on unit change as well now.
- Remove `PUSH` macro
- Remove files that are not needed anymore: curve.txt, fnc_formatNumber.sqf
- Also update sys_radio/fnc_monitorRadios.sqf due to its critical nature.

2017-01-14 22:10 UTC, jonpas requested changes
I think final points in mid-code comments look more disorienting than anything.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_getClientIdLoop.sqf
> +["unit", {[] call FUNC(getClientIdLoopFunc);}] call CBA_fnc_addPlayerEventHandler; // Use EH for immediate sending on unit transfer.
No final point.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_getLanguageName.sqf
> + * Language display name (returns "" if not found) <STRING>
Without `returns`, it's a return value so I'd hope that is clear.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_getSpokenLanguages.sqf
> + * Array of language Ids <Array>
`IDs`?

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_handleGetHeadVector.sqf
> + * Sends the current head direction vector to the teamspeak plugin.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_handleGetPluginVersion.sqf
> + * Handles the return of the current plugin version from teamspeak. Displays messages to the player if any of the versions do not match.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_handleMultiPttKeyPress.sqf
> + * Used to handle a keypress of multiPttKeyPress
Missing final point.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_handleMultiPttKeyPressUp.sqf
> + * Used to handle key up of multiPttKeyPress
Missing final point.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_isMuted.sqf
> + * This function determines is used to check if the unit should be muted on teamspeak or not.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_localStartSpeaking.sqf
> + * Function for handling the local player start speaking event.
`Handles the local ...`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_localStopSpeaking.sqf
> + * Function for handling the local player stop speaking event.
`Handles the local ...`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_muting.sqf
> + * Sets up the per frame event handler to mute and unmute clients on teamspeak. The muting occurs to optimize teamspeak bandwidth as voice data is not sent for muted clients.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_muting.sqf
> +                            };
Not sure if that's clearer, but could be written as
`_muted = [1, 0] select (_remoteUser in GVAR(speakers));`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_pong.sqf
> + * Handler for recieving pong messages from the teamspeak plugin. This is called periodically as it provides a simple check to make sure teamspeak isis still connected to the game.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_processDirectSpeaker.sqf
> + * Calculates the information required by teamspeak for a direct speech speaker.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_processDirectSpeaker.sqf
> + * Parameters to send to teamspeak <ARRAY>
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_processRadioSpeaker.sqf
> + * Calculates the information required by teamspeak for a radio speaker.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_processRadioSpeaker.sqf
> + * Parameters to send to teamspeak  <ARRAY>
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_remoteStartSpeaking.sqf
> + * 0: Teamspeak ID of talking player <STRING>
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_remoteStartSpeaking.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_remoteStopSpeaking.sqf
> + * 0: Teamspeak ID of talking player <STRING>
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_remoteStopSpeaking.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_setSpeakingLanguage.sqf
> + * Successful <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_showBroadCastHint.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_speaking.sqf
> + * Sets up the the per frame event handler for processing all the speaking data which in turn will send data to teamspeak.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_spectatorOff.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_spectatorOn.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_switchChannelFast.sqf
> + * Handles the channel switching keybind
Missing final point.

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_switchChannelFast.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_switchRadioEar.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_toggleHeadset.sqf
> + * Handled <BOOLEAN>
`<BOOL>`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_ts3idToPlayer.sqf
> + * Retrieves the game object of a player from a teamspeak ID.
`TeamSpeak`

2017-01-14 22:10 UTC, jonpas commented on addons/sys_core/fnc_utilityFunction.sqf
> + * Setups some utility per frame event handlers.
`Sets up`

2017-01-15 22:18 UTC, Sniperhid commented on addons/sys_core/fnc_muting.sqf
> +                            };
This is actually slower than the original code

2017-01-15 22:27 UTC, jonpas approved these changes

2017-01-15 22:37 UTC, merged