Eradicating all existance of NO_DEDICATED macro
IDI-Systems/acre2 pull request #190
Opened 2017-01-28 10:34 UTC by TheMagnetar

**When merged this pull request will:**
- Removes all traces of existence of the NO_DEDICATED macro
- Needs proper testing on Dedicated (I need to first fix DirectX for building acre...)

2017-01-28 13:29 UTC, jonpas requested changes
Partial review.

2017-01-28 13:29 UTC, jonpas commented on addons/sys_attenuate/XEH_preInit.sqf
> +if (!hasInterface) exitWith {
One thing I meant when I said streamline preInit files is things like this. In this case it should look like this for easiest readability:
```
#include "script_component.hpp"

ADDON = false;

PREP_RECOMPILE_START;
#include "XEH_PREP.hpp"
PREP_RECOMPILE_END;

if (hasInterface) then {
    GVAR(attenuationCache) = HASH_CREATE;
};

ADDON = true;
```

2017-01-28 13:29 UTC, jonpas commented on addons/sys_components/XEH_postInit.sqf
> +if (!hasInterface) exitWith {};
Hmm, we should just remove that file, it has no content. 😆

2017-01-28 19:31 UTC, TheMagnetar commented on addons/sys_components/XEH_postInit.sqf
> +if (!hasInterface) exitWith {};
Agreed, none of the other branches use this file anyhow

2017-01-28 19:38 UTC, TheMagnetar commented on addons/sys_attenuate/XEH_preInit.sqf
> +if (!hasInterface) exitWith {
OK, This is the other way around. While this improves readability in shorter files, longer ones like sys_core (XEH_postInit), the solution taken here and started by snippers is more clear in my opinion.

2017-02-05 17:03 UTC, TheMagnetar commented
This has been tested in a dedicated without RPT errors.

2017-02-05 18:29 UTC, jonpas commented
Will merge for 2.5.0.

2017-02-05 18:29 UTC, jonpas approved these changes

2017-02-05 21:35 UTC, jonpas requested changes

2017-02-05 21:35 UTC, jonpas commented on addons/sys_antenna/XEH_postInit.sqf
> +if (hasInterface) then {
`if (!hasInterface) exitWith {};` would make more sense here, less indentation needed. It's only for preInit that we can't just exit early due to `˙ADDON = false/true;`.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_attenuate/XEH_preInit.sqf
>  PREP_RECOMPILE_START;
`GVAR(attenuationCache) = HASH_CREATE;` should be inside `if (hasInterface) then {`

2017-02-05 21:35 UTC, jonpas commented on addons/sys_io/XEH_preInit.sqf
> +
No empty line.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_list/XEH_postInit.sqf
> +if (hasInterface) then {
Let's keep `!hasInterface -> exitWith` here as well.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_prc343/XEH_preInit.sqf
> +if (!hasInterface) exitWith {
`if (hasInterface)` around `GVAR` and `DGVAR`.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_radio/XEH_postInit.sqf
> +if (hasInterface) then {
Let's keep `!hasInterface -> exitWith` here as well.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_radio/XEH_preInit.sqf
> +if (!hasInterface) exitWith {
Same as above, whatever is below here inside `if (hasInterface)`.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_sem52sl/XEH_preInit.sqf
> +if (!hasInterface) exitWith {
Same as above.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_server/XEH_postInitClient.sqf
> +if (hasInterface) then {
Let's keep `!hasInterface -> exitWith` here as well.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_signal/XEH_preInit.sqf
> +    FUNC(handleEndTransmission) = {
This should be a separate function, but maybe leave that for another PR.

2017-02-05 21:35 UTC, jonpas commented on addons/sys_sounds/XEH_postInit.sqf
> +if (hasInterface) then {
Let's keep `!hasInterface -> exitWith` here as well.

2017-02-06 08:37 UTC, TheMagnetar commented on addons/sys_signal/XEH_preInit.sqf
> +    FUNC(handleEndTransmission) = {
This particular instance of handleEndTransmission is not used anywhere else. Maybe it should be removed.

2017-02-06 14:17 UTC, jonpas commented on addons/sys_attenuate/XEH_preInit.sqf
>  PREP_RECOMPILE_START;
Solve but is not on this line so this thing does not disappear!

2017-02-06 20:22 UTC, jonpas approved these changes

2017-02-06 20:26 UTC, TheMagnetar commented on addons/sys_signal/XEH_preInit.sqf
> +    FUNC(handleEndTransmission) = {
Moved to another file. See #208

2017-02-16 16:55 UTC, merged