Sem70
IDI-Systems/acre2 pull request #199
Opened 2017-02-04 22:03 UTC by Soldia1138

**When merged this pull request will:**
- Add the SEM70 (ACRE_SEM70), a backpack radio designed for and used by the German Army
- Add a automatic channel selection for the first time in ACRE

2017-02-06 13:40 UTC, Sniperhid reviewed
This is my take a quick-look at the files review.

I am intending to take a bit of look into the UI stuff later to check for issues that popped up while developing the SEM52SL.

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_modes/fnc_sem70akw_muting.sqf
> + */
All sys_modes function headers have already sorted, please fill in the header

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_modes/fnc_sem70akw_speaking.sqf
> + */
All sys_modes function headers have already sorted, please fill in the header

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_modes/fnc_sem70akw_muting.sqf
> +    (_frequenciesTX isEqualTo _frequenciesRX)
Lazy eval would improve the speed here.

```sqf
(_modeTX == "sem70AKW" && _modeRX == "sem70AKW") &&  (_frequenciesTX isEqualTo _frequenciesRX)
```

to

```sqf
(_modeTX == "sem70AKW" && {_modeRX == "sem70AKW"}) && {_frequenciesTX isEqualTo _frequenciesRX})
```

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_sem70/CfgAcreRadios.hpp
> +        sensitivityMin = -117;
I imagine with the SEM70 being older than AN/PRC-117F this value should probably be higher.

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_sem70/functions/fnc_presetInformation.sqf
> +*/
I think the presets `default2`, `default3` and `default4` should be added.

2017-02-06 13:40 UTC, Sniperhid commented on addons/sys_sem70/CfgAcreSounds.hpp
> +};
This should be merged into `sys_sounds/CfgAcreSounds.hpp` the SEM52SL does it this way best for consistency

2017-02-06 13:56 UTC, jonpas requested changes
Headers are also using 2 space indentation instead of 4.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_core/fnc_processRadioSpeaker.sqf
> +if(_radioId == "") exitWith { false };
Space after `if`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_core/fnc_processRadioSpeaker.sqf
> +params["_unit","_playerRadios"];
Space after `params`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_modes/CfgAcreRadioModes.hpp
> +        speaking = QUOTE(DFUNC(sem70akw_speaking));
Could use `QFUNC()` in those two.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_modes/fnc_sem70akw_muting.sqf
> +if(
Space after `if`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_modes/fnc_sem70akw_muting.sqf
> +        _match = true;
One indent less.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_modes/fnc_sem70akw_speaking.sqf
> +params["_tx", "_txRadioId", "_rx", "_rxRadioId"];
Space after `params`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgAcreRadios.hpp
> +class CfgAcreComponents
Opening brace on same line.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgAcreRadios.hpp
> +        connectors[] =     {
Proper indentation from here to end of file (`something = something;` without the amount of spaces).

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgAcreSounds.hpp
> +//CfgAcreSounds.hpp
Redundant comment.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgEventhandlers.hpp
> +    class ADDON    {
Spaaaaces.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgEventhandlers.hpp
> +    class ADDON    {
Spaaaaces.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgVehicles.hpp
> +//CfgVehicles.hpp
Redundant comment.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgWeapons.hpp
> +#define WeaponNoSlot        0    // dummy weapon
Single space between define name and value.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgWeapons.hpp
> +    class ACRE_SEM70 : ACRE_BaseRadio {
`CLASS:` without space between class and semi-colon.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgWeapons.hpp
> +        model = QUOTE(PATHTOF(data\model\sem70.p3d));
`QPATHTOF()` on both of those.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgWeapons.hpp
> +        class ItemInfo
Opening brace on same line.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/CfgWeapons.hpp
> +        class Library
Opening brace on same line.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/RadioDialogClasses.hpp
> +class SEM70_RscBackground
Opening brace on same line - entire file.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/RadioDialogClasses.hpp
> +  type = CT_BUTTON;
4 spaces indentation!

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/XEH_post_init.sqf
> +#include "script_component.hpp"
File should be named `XEH_postInit.sqf`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/XEH_pre_init.sqf
> +#include "script_component.hpp"
File should be named `XEH_preInit.sqf`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/XEH_pre_init.sqf
> +NO_DEDICATED;
We are getting rid of that macro.

Replace from here to end with:
```
if (hasInterface) then {
    GVAR(manualChannel) = 10;
    GVAR(currentRadioId) = -1;

    // UI Variables
    GVAR(backlightOn) = false;
    GVAR(displayButtonPressed) = false;
};

ADDON = true
```

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/config.cpp
> +class CfgPatches
Opening brace on same line.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/functions/__PREP__.sqf
> +
No empty line.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/functions/fnc_clearDisplay.sqf
> +params["_display"];
Space after `params`.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/functions/fnc_onChannelStepKnobTurn.sqf
> + if(_key == 0) then {
Space after `if` - rest of file as well.

2017-02-06 13:56 UTC, jonpas commented on addons/sys_sem70/functions/fnc_onDisplayButtonPress.sqf
> +params["_control"];
I'll stop commenting about those here, should just take a search and replace thing anyways to convert all of those.

2017-02-06 18:54 UTC, Soldia1138 commented on addons/sys_sem70/CfgAcreRadios.hpp
> +class CfgAcreComponents
This is the same for all Configs in ACRE... need a separate issue/PR for that

2017-02-06 18:55 UTC, Soldia1138 commented on addons/sys_sem70/CfgAcreRadios.hpp
> +        connectors[] =     {
Again...this is in-line with the rest of acre. New PR would be the best solution

2017-02-06 18:56 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +    class ACRE_SEM70 : ACRE_BaseRadio {
Again :smile:

2017-02-06 18:59 UTC, jonpas commented on addons/sys_sem70/CfgAcreRadios.hpp
> +class CfgAcreComponents
Ignore it then, I just commented what I saw. 😆

2017-02-06 19:03 UTC, Soldia1138 commented on addons/sys_modes/CfgAcreRadioModes.hpp
> +        speaking = QUOTE(DFUNC(sem70akw_speaking));
#206

2017-02-06 19:03 UTC, Soldia1138 commented on addons/sys_sem70/CfgAcreRadios.hpp
> +        connectors[] =     {
#206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +#define WeaponNoSlot        0    // dummy weapon
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/functions/__PREP__.sqf
> +
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/config.cpp
> +class CfgPatches
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/RadioDialogClasses.hpp
> +  type = CT_BUTTON;
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/RadioDialogClasses.hpp
> +class SEM70_RscBackground
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +        class Library
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +        class ItemInfo
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +        model = QUOTE(PATHTOF(data\model\sem70.p3d));
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:04 UTC, Soldia1138 commented on addons/sys_sem70/CfgWeapons.hpp
> +    class ACRE_SEM70 : ACRE_BaseRadio {
https://github.com/IDI-Systems/acre2/issues/206

2017-02-06 19:05 UTC, Soldia1138 commented on addons/sys_sem70/CfgAcreRadios.hpp
> +        sensitivityMin = -117;
We do not have any documentation on this. And tbh I think most of the values are "best guess"

2017-02-18 22:30 UTC, Sniperhid commented
Tested locally largely looks good, just a few comments.

- Lit display is it intentional that the display instantly goes off or should it be a delay after the button is pressed?
- This one is more of a note. The frequency precision issue - This was an issue with the SEM52SL I wasn't able to reproduce this issue with the SEM70 so it may not exist. The fix for the SEM52 - https://github.com/IDI-Systems/acre2/pull/122
- The approach taking with the frequency knobs is an interesting one which passes off the actual frequency setting into `addons/sys_sem70/radio/fnc_setCurrentChannel.sqf`. I think it would be better to change the setting of the frequencyTX/frequencyRX directly in the UI function using the setChannel Data event like in the SEM52 - https://github.com/IDI-Systems/acre2/blob/8ed080236e72bfc45300748bcae8b743884039e6/addons/sys_sem52sl/functions/fnc_onChannelKnobPress.sqf#L48
It seems there is a possability that the value of manualChannelSelection will be different for various clients - this could become an issue if various network events are still being synced. In which case the data values would cause a desync between some clients and the server.

2017-02-19 11:42 UTC, TheMagnetar requested changes
Misspelling error in sound configuration.

2017-02-19 11:42 UTC, TheMagnetar commented on addons/sys_sounds/CfgAcreSounds.hpp
>          sound = "\idi\acre\addons\sys_sounds\sounds\sem52knob.b64";
There is a misspelling error in here: sound is referenced as sem52knob.b64 but the file name is `semknob.b64`

2017-02-22 19:31 UTC, Soldia1138 commented on addons/sys_sem70/functions/__PREP__.sqf
> +
This is interesting...locally the line isn't there anymore for me...

2017-02-22 20:40 UTC, Soldia1138 commented
Sniperhid: 
- Yes, this is correct. It is intended to only lit the display while the knob is depressed
- Will save that for a potential fix later on
- Will look into that one, thx

2017-02-25 10:58 UTC, Raspu86 commented
I'm very much looking forward to this! Great job @Soldia1138! We do need some documentation for it tough, especially the automatic channel selection for which i haven't wrapped my head around yet

2017-02-27 16:28 UTC, jonpas commented on addons/sys_sem70/functions/__PREP__.sqf
> +
Hah!

2017-02-27 16:28 UTC, jonpas approved these changes

2017-03-08 12:48 UTC, TheMagnetar approved these changes

2017-03-08 12:55 UTC, jonpas requested changes

2017-03-08 12:55 UTC, jonpas commented on docs/wiki/frameworks/adding-new-antenna.md
> +<<<<<<< HEAD
Unresolved conflicts.

2017-03-08 20:25 UTC, jonpas approved these changes

2017-03-08 20:36 UTC, merged