Move handleEndTransmission to its own file
IDI-Systems/acre2 pull request #208
Opened 2017-02-06 20:21 UTC by TheMagnetar

**When merged this pull request will:**
- Moves FUNC(handleEndTransmission) in sys_signal/XEH_PreInit.hpp to its own file

2017-02-06 20:30 UTC, jonpas requested changes

2017-02-06 20:30 UTC, jonpas commented on addons/sys_signal/fnc_handleEndTransmission.sqf
> + #include "script_component.hpp"
Space at start.

2017-02-06 20:30 UTC, jonpas commented on addons/sys_signal/fnc_handleEndTransmission.sqf
> + params ["", "", "_data"];
Space at start copy pasting is not always nice. 😆

2017-02-06 20:30 UTC, jonpas commented on addons/sys_signal/fnc_handleEndTransmission.sqf
> + * nil
Just write `None`.

2017-02-06 20:41 UTC, TheMagnetar commented on addons/sys_signal/fnc_handleEndTransmission.sqf
> + params ["", "", "_data"];
xDDDDDDDD

2017-02-06 21:08 UTC, jonpas approved these changes

2017-02-09 12:49 UTC, closed without merging

2017-02-16 16:41 UTC, jonpas commented
Replaced by #216