Added missing Czech translation of sys_core
IDI-Systems/acre2 pull request #212
Opened 2017-02-13 22:00 UTC by Kllrt

**When merged this pull request will:**
- Describe what this pull request will do
- Each change in a separate line
- Respect the [SQF](https://github.com/IDI-Systems/acre2/wiki/Coding-Guidelines-(SQF)) and [C++](https://github.com/IDI-Systems/acre2/wiki/Coding-Guidelines-(CPP)) Coding Guidelines

2017-02-13 22:01 UTC, Sniperhid approved these changes

2017-02-13 22:08 UTC, jonpas requested changes

2017-02-13 22:08 UTC, jonpas commented on addons/sys_core/stringtable.xml
> +</Project>
Missing newline.

2017-02-14 07:06 UTC, Kllrt commented on addons/sys_core/stringtable.xml
> +</Project>
That's weird, I didn't change that. Could it be Tabler issue?

2017-02-14 08:37 UTC, jonpas commented on addons/sys_core/stringtable.xml
> +</Project>
Right.

2017-02-14 08:37 UTC, jonpas approved these changes

2017-02-16 15:37 UTC, merged