acre_api_fnc_setCustomSignalFunc - reset fix
IDI-Systems/acre2 pull request #227
Opened 2017-02-22 11:36 UTC by Dorbedo

**When merged this pull request will:**
- fixes the possibility to reset the function to default behavior
- changes the reset value from an emtpy array (nil) into an emtpy code({})

2017-02-22 13:14 UTC, jonpas requested changes

2017-02-22 13:14 UTC, jonpas commented on addons/api/fnc_setCustomSignalFunc.sqf
> +If !(_this params [["_code",{},[{}]]]) exitWith {
Lower-case if.

2017-02-22 13:14 UTC, jonpas commented on addons/api/fnc_setCustomSignalFunc.sqf
> +If (_code isEqualTo {}) then {
Lower-case if.

2017-02-22 22:42 UTC, jonpas submitted a review, later dismissed

2017-02-24 17:44 UTC, Sniperhid commented
What is the advantage of this?

`[] call acre_api_fnc_setCustomSignalFunc;` - Presently works fine to reset the custom signal function.

2017-02-24 22:19 UTC, Dorbedo commented
Did you try it in sheduled environment?

2017-02-25 01:18 UTC, Sniperhid approved these changes

2017-02-25 01:19 UTC, Sniperhid commented
Good point! This does indeed fix it in that case.

2017-02-25 01:42 UTC, merged