4 nec2 antenna calculation
IDI-Systems/acre2 pull request #244
Opened 2017-02-26 00:51 UTC by Soldia1138

**When merged this pull request will:**
- Port all antenna data to generation by 4NEC2
- Add missing antennas 
- Change C++ Code to handle data

2017-02-26 23:38 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +title: Adding a new antenna
Use `Adding New Antenna` and rename file to `adding-new-antenna.md`.

2017-02-26 23:44 UTC, jonpas requested changes
Linsk to other pages in same directory can be shoretened to just the file name without extension.

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +Every radio in ACRE can be equipped with at least one antenna. Since radios usually have specific antennas designed and tuned for the radio and the frequency range used, it is likely one must add a n
- `ACRE2`
- `[new radio](creating-new-radio)`

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +In order to allow an antenna to work properly in ACRE, there are a few required config entries and most importantly a set of gain data covering the desired frequency range. The gain data is used by t
- `ACRE2`
- `[Radio Loss](radio-signal-loss)`

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +Antennas themselves are defined in the `sys_antennas` component of ACRE2 [sys_antennas\CfgAcreComponents.hpp](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_antenna/CfgAcreComponents.hpp
Forward slash in path.

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +    class ACRE_2HALFINCH_UHF_TNC : ACRE_BaseAntenna {
No space before `:`

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +        orient = 90;    // in degrees off of flat plane
One space before comment.

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +        binaryGainFile = "\idi\acre\addons\sys_antenna\binary\VHF_1.2m_whip_gain.aba";
Can just use `QPATHTOF(binary\<antenna>.aba)`

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +
No empty line.

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +As ACRE tries to simulate radios as close to reality as possible, the gain data used is coming from a tool used for antenna and electromagnetic effects simulation. This tool is called 4NEC2 and can b
- `ACRE2`
- No question mark at end of URL.

2017-02-26 23:44 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +The first step after opening 4NEC2 is to create a model of the antenna. Usually it is more than sufficient to use a vertical wire and a simple ground setting. These models are stored in the _.nec_ fo
`.nec` in code ticks.

2017-02-26 23:48 UTC, jonpas requested changes
Taaabs.

2017-02-26 23:48 UTC, jonpas commented on addons/sys_antenna/CfgAcreComponents.hpp
> +        binaryGainFile = "\idi\acre\addons\sys_antenna\binary\Thales_100cm_Whip_gain.aba";
`QPATHTOF(binary\Thales_100cm_Whip_gain.aba)` in all.

2017-02-26 23:48 UTC, jonpas commented on addons/sys_antenna/CfgAcreComponents.hpp
> +    class ACRE_100CM_VHF_TNC : ACRE_BaseAntenna {
You like spaces? 💃

2017-02-26 23:48 UTC, jonpas commented on addons/sys_antenna/CfgAcreComponents.hpp
> +        name            = "SEM52SL Antenna Short (0.4m)";
Just one space on each side of `=`.

2017-02-26 23:48 UTC, jonpas commented on extensions/src/ACRE2Arma/signal/antenna/antenna.cpp
> +
Whitespace.

2017-02-26 23:48 UTC, jonpas commented on tools/antenna_create_binary.py
> +#	Read Values from Output file
Tabs (whole file).

2017-02-26 23:48 UTC, jonpas commented on extras/antennas/AT-271.inp
> +CM PRC343 Antenna
Sure? 🤔

2017-02-26 23:48 UTC, jonpas commented on extensions/src/ACRE2Arma/signal/antenna/antenna.cpp
> +	LOG(TRACE) << "Elevation Antenna : " << elev_antenna;
Tabs (whole file).

2017-02-27 15:21 UTC, Soldia1138 commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +In order to allow an antenna to work properly in ACRE, there are a few required config entries and most importantly a set of gain data covering the desired frequency range. The gain data is used by t
But that isn't in the same directory, is it?

2017-02-27 15:55 UTC, jonpas commented on docs/wiki/frameworks/adding-a-new-antenna.md
> +In order to allow an antenna to work properly in ACRE, there are a few required config entries and most importantly a set of gain data covering the desired frequency range. The gain data is used by t
Right, my bad, should be `[Radio Loss](/wiki/user/radio-signal-loss)` then.

2017-02-27 16:25 UTC, jonpas submitted a review, later dismissed

2017-03-05 02:59 UTC, jonpas commented
Added #29 reference to OP as this PR adds the SEM52SL antenna.

2017-03-07 20:28 UTC, jonpas approved these changes

2017-03-08 10:35 UTC, merged