Box with radios
IDI-Systems/acre2 pull request #265
Opened 2017-03-18 14:44 UTC by TheMagnetar

**When merged this pull request will:**
- Adds  a box with radios.
- Closes #263 

- [ ] Add a custom box model.

2017-03-18 14:47 UTC, jonpas requested changes

2017-03-18 14:47 UTC, jonpas commented on addons/sys_radio/CfgVehicles.hpp
> +        author = "ACRE2-Team";
`author = ECSTRING(main,Author);`

2017-03-18 14:47 UTC, jonpas commented on addons/sys_radio/CfgVehicles.hpp
> +        accuracy = 1000;
Is that needed?

2017-03-18 18:29 UTC, TheMagnetar commented on addons/sys_radio/CfgVehicles.hpp
> +        accuracy = 1000;
yes, NATO_Box_Base has nothing of this defined. It is totally empty.

2017-03-18 18:32 UTC, PabstMirror commented
I think it needs to be in the `units[] ={}` array in cfgPatches for it to show in 3den/zeus

2017-03-18 18:33 UTC, jonpas commented
Yes it does.

2017-03-20 09:05 UTC, jonpas requested changes

2017-03-20 09:05 UTC, jonpas commented on addons/sys_radio/stringtable.xml
> +            <English>[ACRE2] Radio Supply Crate</English>
Not used?

2017-03-26 17:19 UTC, jonpas commented on addons/sys_radio/stringtable.xml
> +            <English>[ACRE2] Radio Supply Crate</English>
Done.

2017-03-26 17:40 UTC, jonpas approved these changes

2017-03-26 17:40 UTC, merged