Fix distortion test plugin and map gen compilation
IDI-Systems/acre2 pull request #280
Opened 2017-04-02 13:15 UTC by jonpas

**When merged this pull request will:**
- Fix compile errors in `DistortionTestPlugin` and `mapgen`
- Update `DistortionTestPlugin` with TeamSpeak3 Channel Switching functionalities (copy)
- Add omni-directional support to `mapgen`

2017-04-04 09:40 UTC, jonpas commented on extensions/src/ACRE2Arma/signal/signal.hpp
> +                bool omnidirectional = args_.as_int();
Need to use `bool omnidirectional = args_.as_int() == 1;`.

2017-04-04 21:05 UTC, TheMagnetar requested changes
I do not think that this  is necessary in c++. 1 is already "true". There is no difference.

2017-04-04 21:14 UTC, jonpas commented
It is done the same way on L108, I think doing it explicitly might be cleaner for consistency as it is already used like that.

2017-04-08 17:55 UTC, jonpas commented on extensions/src/ACRE2Arma/signal/signal.hpp
> +                float rx_antenna_height, glm::vec3 tx_pos_, glm::vec3 tx_dir_, antenna_p &tx_antenna_, antenna_p &rx_antenna_, float frequency_, float power_, float sinad_, bool omnidirectional_
Would actually be good to use that new variable on L373...

2017-04-08 21:54 UTC, jonpas commented
Tested and works, good to go.

2017-04-08 23:07 UTC, TheMagnetar approved these changes

2017-04-08 23:08 UTC, merged