Improvements on external radios
IDI-Systems/acre2 pull request #285
Opened 2017-04-04 20:13 UTC by TheMagnetar

**When merged this pull request will:**
- Disables the option of opening the radio by the external user.
- Closes #284.

2017-04-04 20:24 UTC, jonpas commented on addons/ace_interact/fnc_radioChildrenActions.sqf
> +    _action = ["acre_connectors", "Connectors", "\idi\acre\addons\ace_interact\data\icons\connector4.paa", {}, {true}, {_this call FUNC(generateConnectors);}, _params] call ace_interact_menu_fnc_crea
Stringtable?

2017-04-04 20:44 UTC, TheMagnetar commented on addons/ace_interact/fnc_radioChildrenActions.sqf
> +    _action = ["acre_connectors", "Connectors", "\idi\acre\addons\ace_interact\data\icons\connector4.paa", {}, {true}, {_this call FUNC(generateConnectors);}, _params] call ace_interact_menu_fnc_crea
oops, mixed  with racks...

2017-04-07 10:18 UTC, jonpas requested changes

2017-04-07 10:18 UTC, jonpas commented on addons/sys_prc117f/fnc_openGui.sqf
> +// Prevent radio from being opened if it is externally used.
No final dot. In other files too.

2017-04-07 10:18 UTC, jonpas commented on addons/sys_external/stringtable.xml
> +            <English>Radio is used externally. Configuration must be made by the owner.</English>
Does that even fit standard message box height?

2017-04-07 17:37 UTC, TheMagnetar commented on addons/sys_external/stringtable.xml
> +            <English>Radio is used externally. Configuration must be made by the owner.</English>
yes.

2017-04-07 17:55 UTC, jonpas commented on addons/sys_external/stringtable.xml
> +            <English>Radio is used externally. Configuration must be made by the owner.</English>
What about `Radio used externally. Only owner may configure.`?

2017-04-07 18:04 UTC, TheMagnetar commented on addons/sys_external/stringtable.xml
> +            <English>Radio is used externally. Configuration must be made by the owner.</English>
Yeah, much better!

2017-04-07 18:07 UTC, jonpas approved these changes

2017-04-11 04:32 UTC, Soldia1138 approved these changes
Looking good for me. Resolve that merge conflict and we can merge

2017-04-11 05:12 UTC, merged