Limit open radio
IDI-Systems/acre2 pull request #336
Opened 2017-05-05 18:30 UTC by TheMagnetar

**When merged this pull request will:**
- Prevent two or more players from opening the same radio GUI. This is important for radio racks and man-pack radios.
- Allow external manpack radios to be configured by both owner and external user.

2017-05-05 20:39 UTC, jonpas commented on addons/sys_rack/stringtable.xml
> +            <English>Radio interface is opened by another player.</English>
Too immersion breaking! 😆 
Something like "Radio in hand of an external user." might be better.

2017-05-05 20:40 UTC, jonpas requested changes

2017-05-05 20:40 UTC, jonpas commented on addons/sys_external/fnc_initRadio.sqf
> +// To prevent the GUI from being simultaneously opened.
No final dot.

2017-05-05 21:22 UTC, Soldia1138 approved these changes

2017-05-05 21:22 UTC, Soldia1138 commented on addons/sys_external/fnc_initRadio.sqf
> +[_radioId, "setState", ["isGuiOpened", false]] call EFUNC(sys_data,dataEvent);
Although I personally don't like states beginning with a verb, this is already the case with other states. So we can leave it as it is

2017-05-05 21:23 UTC, TheMagnetar commented on addons/sys_external/fnc_initRadio.sqf
> +[_radioId, "setState", ["isGuiOpened", false]] call EFUNC(sys_data,dataEvent);
No problem, I  can change  it.

2017-05-05 21:31 UTC, jonpas commented on addons/sys_external/fnc_initRadio.sqf
> +[_radioId, "setState", ["isGuiOpened", false]] call EFUNC(sys_data,dataEvent);
Let's do that in another PR later then, consistency is more important.

2017-05-07 14:36 UTC, jonpas approved these changes

2017-05-07 14:36 UTC, merged