Fix privatization - warnings reported by LordGolias' SQF analyser
IDI-Systems/acre2 pull request #347
Opened 2017-05-12 22:15 UTC by jonpas

**When merged this pull request will:**
- Work on #346 

TODO:
- [ ] All `sys_<radio>` components

2017-05-26 13:49 UTC, TheMagnetar requested changes

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_core/fnc_getCompartment.sqf
> +if !(_compartment isEqualType "") then {
Just for consistency with the other files:
(_compartment isEqualType "STRING")

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_prc148/fnc_preset_information.sqf
>              if (abs(_x-_frequency) <= 0.25) exitWith {
abs (_x - _frequency)

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_prc148/fnc_preset_information.sqf
>              if (abs(_x-_frequency) <= 0.25) exitWith {
same as above

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_prc148/fnc_preset_information.sqf
>              if (abs(_x-_frequency) <= 0.25) exitWith {
same as above

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_prc152/menus/fnc_delayFunction.sqf
>          [(_this select 1)] call CBA_fnc_removePerFrameHandler;
No brackets

2017-05-26 13:49 UTC, TheMagnetar commented on addons/sys_radio/fnc_onReturnRadioId.sqf
> +                        [_this] call EFUNC(sys_radio,setActiveRadio);
are you sure about this?

2017-05-26 14:13 UTC, jonpas commented on addons/sys_core/fnc_getCompartment.sqf
> +if !(_compartment isEqualType "") then {
No idea why that is used anywhere, this is shorter and to the point, will change the other files.

2017-05-26 14:13 UTC, jonpas commented on addons/sys_prc148/fnc_preset_information.sqf
>              if (abs(_x-_frequency) <= 0.25) exitWith {
Should go into another PR, has nothing to do with this one.

2017-05-26 14:24 UTC, jonpas commented on addons/sys_radio/fnc_onReturnRadioId.sqf
> +                        [_this] call EFUNC(sys_radio,setActiveRadio);
Why wouldn't I be?

2017-06-08 15:52 UTC, TheMagnetar approved these changes

2017-06-08 16:28 UTC, merged