Update Manual installation instructions for plugin auto-copy
IDI-Systems/acre2 pull request #371
Opened 2017-06-07 00:34 UTC by jonpas

**When merged this pull request will:**
- Title

2017-06-07 09:29 UTC, TheMagnetar requested changes

2017-06-07 09:29 UTC, TheMagnetar commented on docs/wiki/user/installation.md
> +- ACRE2 will try to copy the plugins to your TeamSpeak 3 installation directory. If it can not it will warn you. If it is successful it will tell you.
If it cannot, it will warn you. If it is successful, it will tell you.

2017-06-07 09:29 UTC, TheMagnetar commented on docs/wiki/user/installation.md
> +- ACRE2 will try to copy the plugins to your TeamSpeak 3 installation directory. If it can not it will warn you. If it is successful it will tell you.
same as above.

2017-06-07 12:22 UTC, jonpas commented on docs/wiki/user/installation.md
> +- ACRE2 will try to copy the plugins to your TeamSpeak 3 installation directory. If it can not it will warn you. If it is successful it will tell you.
> Both cannot and can not are acceptable spellings, but the first is much more usual. You would use can not when the ‘not’ forms part of another construction such as ‘not only’.

@Sniperhid wrote that, English is his native language. :P

2017-06-08 16:24 UTC, TheMagnetar approved these changes

2017-06-08 16:27 UTC, merged