New Antenna calculation with better ground
IDI-Systems/acre2 pull request #414
Opened 2017-10-11 21:29 UTC by Soldia1138

The calculation method of antenna data was slightly changed regarding ground settings. 

This should heavily improve the signal quality, esp. in vehicles

2017-10-11 22:14 UTC, jonpas approved these changes

2017-10-11 22:35 UTC, Soldia1138 commented
Will add documentation as well

2017-10-12 12:20 UTC, jonpas requested changes

2017-10-12 12:20 UTC, jonpas commented on docs/wiki/frameworks/adding-new-antenna.md
> +**Ground Settings**: It is highly recommended to set the ground setting to `Perfect gnd` and check the `Connect wire(s) for Z=0 to ground` setting as well. Other ground settings may lead to more real
Add an empty line above to split the paragraphs.

2017-10-12 13:09 UTC, jonpas approved these changes

2017-10-12 13:09 UTC, merged