Ts channel switch enhancements
IDI-Systems/acre2 pull request #423
Opened 2017-10-21 15:24 UTC by tbeswick96

**When merged this pull request will:**
- Added full string comparison. Will search for exact name first. Break if match found.
- Added word comparison. Will search for word matches second. Skip char comparison if match found.
- Char comparison (Levenshtein distance) occurs third.
- Bit of cleanup

2017-10-21 15:30 UTC, TheMagnetar commented
I would prefer avoiding the use of the `auto` type. It makes the code not so clear in my opinion. Since this is a matter of personal preference, I will not ask for a change unless we all decide to.

2017-10-21 15:31 UTC, TheMagnetar commented on extensions/src/ACRE2TS/TS3Client.cpp
> +                auto channelNameString = std::string(channelName);
This is one of the examples where I think that auto should not be used.

2017-10-21 18:40 UTC, jonpas commented
I agree with `auto` usage not being preferable, where it should be one specific type, write out the type. Iterators and other things where it's not as specific or readable, `auto` is good.

2017-10-25 19:44 UTC, TheMagnetar requested changes
It looks really good. It is just those uses of auto keyword. I will update the C++ coding guidelines to reflect this.

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
> +    const auto columnStart = decltype(length1)(1);
Just declare it as the right type, without using auto.

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
> +            const auto oldDiagonal = column[y];
this is also an integer.

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
> +    const auto result = column[length1];
same

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2TS/TS3Client.cpp
> +    const auto columnStart = decltype(length1)(1);
same as above

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2TS/TS3Client.cpp
> +    const auto column = new decltype(length1)[length1 + 1];
same as above

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2TS/TS3Client.cpp
> +    const auto result = column[length1];
use of auto keyword

2017-10-25 19:44 UTC, TheMagnetar commented on extensions/src/ACRE2TS/TS3Client.cpp
> +            const auto oldDiagonal = column[y];
use of auto keyword

2017-11-05 16:48 UTC, tbeswick96 commented
Changes done

2017-11-05 21:02 UTC, TheMagnetar commented
Much appreciated!

2017-11-05 21:02 UTC, TheMagnetar approved these changes

2017-11-05 22:09 UTC, merged