Add API to passthrough ACRE2 keys to custom displays
IDI-Systems/acre2 pull request #437
Opened 2017-11-05 02:37 UTC by jonpas

**When merged this pull request will:**
- Close #372 - Assign keys to Vanilla Spectator (EG Spectator) display

2017-11-05 02:46 UTC, jonpas commented
I am not sure if that's necessary, but I assume most communities using Vanilla Spectator (EG Spectator) hook the ACRE2 Spectator Mode themselves?

2017-11-09 08:04 UTC, Sniperhid approved these changes
Looks great, there are some communities that use vanilla spectator but don't have the technical know how to set this up themselves so pretty sweet!

2017-11-09 08:56 UTC, TheMagnetar requested changes

2017-11-09 08:56 UTC, TheMagnetar commented on addons/api/fnc_addDisplayPassthroughKeys.sqf
> + *
No final ;

2017-11-09 08:56 UTC, TheMagnetar commented on addons/sys_core/fnc_addDisplayPassthroughKeys.sqf
> + *
Same as above

2017-11-09 11:44 UTC, jonpas commented
Tested with EG Spectator and ACE3 Spectator (https://github.com/acemod/ACE3/pull/5735).

2017-11-09 12:56 UTC, TheMagnetar approved these changes

2017-11-09 13:02 UTC, merged