STATE Macro harmonization
IDI-Systems/acre2 pull request #48
Opened 2016-09-19 11:24 UTC by Soldia1138

**When merged this pull request will:**
- Harmonize STATE Macros for radios
- Put STATE Macros to main component

2016-09-28 12:58 UTC, Sniperhid requested changes

2016-09-28 12:58 UTC, Sniperhid commented on addons/sys_prc117f/menus/fnc_changeMenu.sqf
> +SET_STATE(menuSelection , 0);
Due to the way the macros works this becomes some thing like ` ["menuSelection "`

2016-09-28 12:58 UTC, Sniperhid commented on addons/sys_prc152/menus/fnc_changeMenu.sqf
> +SET_STATE(menuSelection , 0);
Same issue again -> `"menuSelection "`

2016-09-28 19:57 UTC, Soldia1138 commented on addons/sys_prc152/menus/fnc_changeMenu.sqf
> +SET_STATE(menuSelection , 0);
Should be fixed by https://github.com/IDI-Systems/acre2/pull/48/commits/50c0de446a85dfa0d8d5fc99457ec22a2b752e47

2016-09-29 00:00 UTC, Sniperhid requested changes
You have fixed the issues however I discored a new issue with the 152/117F menus

```
private _saveName = MENU_SELECTION_VARIABLE(_menu);
SET_STATE(_saveName, _value);
```

is commonly used previously the value of `_saveName` would be used as the variable name e.g. `pgm_preset_number` now instead they are soted on `"_saveName"` instead

2016-10-04 11:54 UTC, Soldia1138 commented
According to my tests, this is working now.

2016-10-05 08:35 UTC, Sniperhid approved these changes

2016-10-05 08:36 UTC, Sniperhid commented
Seconded my testing seems good as well! GJ JP

2016-10-05 08:54 UTC, merged