Allow rack initialisation based on a condition
IDI-Systems/acre2 pull request #534
Opened 2018-05-17 19:10 UTC by TheMagnetar

**Problem descriptioin**
Rack initialisation through API selected always the first player. This could break TvT games where radio presets are assigned depending on the side of the unit.

**When merged this pull request will:**
- Adds an additional argument to API functions `initVehicleRacks` and `addRackToVehicle` that specifies  the condition for a given unit. The first player that matches the side criteria will initialise the rack.

**Update** custom radio presets can be added to racked radios too. Two new API functions have been added for this purpose:

- setVehicleRacksPreset
- getVehicleRacksPreset

Vehicle racks preset have priority over player presets if defined.

2018-05-17 20:54 UTC, Cuel commented
You can use `CBA_fnc_players` instead of all the `(allPlayers - entities "HeadlessClient_F")`

2018-05-21 06:33 UTC, TheMagnetar commented
I have updated the PR in order to make it more general. Now a condition can be specified  in order to match a certain criteria. This allows initialising a rack with a certain radio preset if multiple networks per side are defined by limiting the initialisation to a certain unit.

2018-05-21 16:59 UTC, jonpas requested changes

2018-05-21 16:59 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> + * Initialises all racks in the vehicle. Must be executed in the server. If no side is specified,
Is now condition.

2018-05-21 16:59 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> + * 3: Condition called with argument "_unit" <STRING> (default: "")
Just take code instead of string, no need to `compile`. Should also be advised that it's a pre-compiled function if longer.

2018-05-21 16:59 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> +        } forEach (allPlayers - entities "HeadlessClient_F");
`CBA_fnc_players`

2018-05-21 16:59 UTC, jonpas commented on addons/api/fnc_initVehicleRacks.sqf
> + * 1: Condition called with argument "_unit" <STRING> (default: "")
Same as above.

2018-05-21 16:59 UTC, jonpas commented on addons/api/fnc_initVehicleRacks.sqf
> + * Initialises all racks in the vehicle. Must be executed in the server. If no side is specified,
Same as above.

2018-05-22 14:43 UTC, jonpas requested changes

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> + * 3: Condition called with argument "_unit". If a longer function is given, it should be a precompiled <CODE> (default: "")
`precompiled. <CODE> (default: {})`

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
>              if ([_unit] call compile _condition) then {
No need for `compile` anymore.

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_getVehicleRacksPreset.sqf
> + * Preset name. Empty string if not defined <STRING>
`Preset name ("" if undefined) <STRING>`

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_getVehicleRacksPreset.sqf
> +    ERROR("Vehicle is null");
I forget, doesn't this throw an on-screen error as well? Or is that just `ERROR_WITH_MESSAGE_n`?

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_initVehicleRacks.sqf
> + * 1: Condition called with argument "_unit". If a longer function is given, it should be a precompiled <CODE> (default: "")
`precompiled. <CODE> (default: {})`

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_setVehicleRacksPreset.sqf
> + * 1: Preset name <STRING> (Default: "")
Lowercase `default`.

2018-05-22 14:43 UTC, jonpas commented on addons/api/fnc_setVehicleRacksPreset.sqf
> + * 0: Vehicle <OBJECT> (Default: objNull)
Lowercase `default`.

2018-05-22 14:44 UTC, jonpas requested changes

2018-05-22 14:44 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> +            if ([_unit] call compile _condition) then {
No need for `compile` anymore.

2018-05-22 14:44 UTC, jonpas commented on addons/api/fnc_initVehicleRacks.sqf
> + * 1: Condition called with argument "_unit". If a longer function is given, it should be a precompiled <CODE> (default: "")
`precompiled. <CODE> (default: {})`

2018-05-22 14:44 UTC, jonpas commented on addons/api/fnc_initVehicleRacks.sqf
> +        if ([_unit] call compile _condition) then {
No need for `compile` anymore.

2018-05-22 19:52 UTC, TheMagnetar commented
I did a branch mess between two computers...

2018-05-22 20:10 UTC, jonpas commented on addons/api/fnc_addRackToVehicle.sqf
> + * 3: Condition called with argument "_unit". If a longer function is given, it should be precompiled <CODE>. (default: {})
Dot a word back, you did it right in the other file! 😆

2018-05-22 20:39 UTC, jonpas approved these changes

2018-05-22 20:42 UTC, merged