Enable channel fast switch for racked radios
IDI-Systems/acre2 pull request #543
Opened 2018-06-12 15:01 UTC by tbeswick96

**When merged this pull request will:**
- Add check to fast channel switch to allow fast switching of racked radios
- Rationale is a radio in a rack is usually as easily accessible as a normal radio

2018-06-12 16:10 UTC, TheMagnetar approved these changes

2018-06-12 16:16 UTC, TheMagnetar requested changes
It needs to be considered as well the case where the player has no physical access to the rack. This can be for example a gunman in a helicopter... it would be weird to be able to switch channela when by config definition he is not able to open the radio GUI

2018-06-12 18:15 UTC, tbeswick96 commented
@TheMagnetar THink that is fixed. I've included a check to ensure the radio is accessible

2018-06-20 20:25 UTC, TheMagnetar requested changes

2018-06-21 17:52 UTC, jonpas commented on addons/sys_core/fnc_switchChannelFast.sqf
> +private _isRackRadio = (vehicle acre_player != acre_player) && {_radioId in (([vehicle acre_player] call EFUNC(api,getVehicleRacks)) apply {[_x] call EFUNC(api,getMountedRackRadio)})} && {[_radioId,
`_isRackRadioAccessible` would be more fitting.

2018-06-24 16:58 UTC, TheMagnetar approved these changes

2018-06-24 16:58 UTC, merged