Added actions to use and stop using all racks
IDI-Systems/acre2 pull request #545
Opened 2018-06-12 23:08 UTC by tbeswick96

**When merged this pull request will:**
- Add 2 interactions to main racks node
- One starts use of all racks
- One stops use of all racks

2018-06-20 20:23 UTC, TheMagnetar requested changes

2018-06-21 17:51 UTC, jonpas commented on addons/sys_rack/stringtable.xml
> +        <Key ID="STR_ACRE_sys_rack_useAllRacks">
The other one is actually "useRadio", I don't think it matters much, but consistency is good.

2018-06-21 17:51 UTC, jonpas approved these changes

2018-06-23 06:00 UTC, TheMagnetar requested changes

2018-06-23 06:00 UTC, TheMagnetar commented on addons/sys_rack/fnc_rackListChildrenActions.sqf
> +private _radios = (_racks apply {[_x] call FUNC(getMountedRadio)}) select {_x != "" && {[_x, acre_player] call FUNC(isRadioAccessible)}};
Using `isRadioAccessible` will render the check {_x in ACRE_HEARABLE_RACK_RADIOS} obsolete since lines 50, 52, 60 and 62 since it will always be []

2018-06-25 06:45 UTC, TheMagnetar approved these changes

2018-06-25 06:46 UTC, merged