Scoped enums
IDI-Systems/acre2 pull request #655
Opened 2019-04-01 07:09 UTC by TheMagnetar

**When merged this pull request will:**
- Change some enums to scoped enums.

2019-04-03 22:03 UTC, jonpas requested changes
Does this fit our guidelines? I am not sure what @NouberNou thinks of enum namings.

EOF unrelated, but might as well since some did get cleaned.

Looking good otherwise.

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/SoundEngine.cpp
>  }
```suggestion
}

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/Self.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/RpcEngine.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/KeyHandlerEngine.cpp
>  */
```suggestion
*/

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/ext_reset.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/getClientID.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/getPluginVersion.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/loadSound.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/localMute.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/ping.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/playSound.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/setMuted.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/setPTTKeys.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/setSelectableVoiceCurve.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/setSoundSystemMasterOverride.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/stopRadioSpeaking.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Core/updateSelf.h
>  };
```suggestion
};

```

2019-04-03 22:03 UTC, jonpas commented on extensions/src/ACRE2Shared/IRpcFunction.h
>  };
```suggestion
};

```

2019-04-03 22:19 UTC, TheMagnetar commented
Leave those spaces. They are all over the code due to the use of macros.

2019-04-03 22:24 UTC, jonpas commented
What spaces? I didn't remove them before closing braces, I just added a newline at EOF. No clue what GitHub did, it doesn't even show a space before it in the diff though.

2019-04-04 17:38 UTC, jonpas commented
Still some left? (I resolved those committed.)

2019-04-07 15:18 UTC, jonpas approved these changes

2019-04-21 06:20 UTC, merged