Cleanup. Remove compile warnings. New  program to generate fakewrp
IDI-Systems/acre2 pull request #688
Opened 2019-06-03 19:50 UTC by TheMagnetar

**When merged this pull request will:**
- Fixes routines mapgen and acre_map_test.
- Use of Enum class  in landscape.cpp instead of default values (-2, -1 and 0).
- Remove compile warnings.
- New routine to generate ACRE wrp formats.

![image](https://user-images.githubusercontent.com/11097475/58830009-93af8900-8649-11e9-95f3-12d92e430c4c.png)

2019-06-15 18:35 UTC, TheMagnetar commented
This is ready for review. I need to test GM regen in game, but it is just a binary file.

2019-06-16 17:10 UTC, jonpas requested changes

2019-06-16 17:10 UTC, jonpas commented on extensions/src/ACRE2Arma/common/wrp/landscape.cpp
> +    out.write((char *)&version, sizeof(uint32_t));       // Version
C++-style casts?

2019-06-16 19:17 UTC, TheMagnetar commented on extensions/src/ACRE2Arma/common/wrp/landscape.cpp
> +    out.write((char *)&version, sizeof(uint32_t));       // Version
better not in here.

2019-06-16 19:18 UTC, jonpas approved these changes

2019-06-17 13:25 UTC, merged