Default radio volume
IDI-Systems/acre2 pull request #731
Opened 2019-07-24 03:00 UTC by synixebrett

**When merged this pull request will:**
- Close #730 

Doesn't work with the sem52sl

2019-07-24 05:14 UTC, TheMagnetar commented
SEM52SL initialises like any other radio.  https://github.com/IDI-Systems/acre2/blob/master/addons/sys_sem52sl/radio/fnc_initializeRadio.sqf#L79

2019-07-24 05:15 UTC, synixebrett commented
I may be wrong, but I don't think the values line up with other radios.

All the others either step by 10 or 20

2019-07-24 05:20 UTC, TheMagnetar commented
you are right (knob has 8 positions), but I see bug reports like... hey my volume is not properly set in the sem52sl...

2019-07-24 05:23 UTC, synixebrett commented
Yeah I'm not sure what to do about it, setting it to a value off the knobs could result in weird behaviour when using the knobs. I guess I could just map the value to the closest option for the sem52sl

2019-07-24 07:52 UTC, TheMagnetar commented
Defaulting it to the closest value should be the way to go.

2019-07-31 09:45 UTC, synixebrett commented
It doesn't use the closest value, but it rounds up to the nearest value. 80 will go up to 87.5 rather than going down to 75.

2019-07-31 13:06 UTC, jonpas reviewed
Can we macro this for readability and single point of change?

Or comment at least, it's not obvious what the code does and why.

2019-08-04 16:24 UTC, jonpas requested changes

2019-08-04 16:24 UTC, jonpas commented on addons/sys_core/initSettings.sqf
> +] call CBA_Settings_fnc_init;
Should use `CBA_fnc_addSetting`.

2019-08-04 16:24 UTC, jonpas commented on addons/sys_sem52sl/radio/fnc_initializeRadio.sqf
> +_volume = _volume + .125 - (_volume % .125);
Comment what this does, or macro with self-explanatory name.

2019-08-04 17:35 UTC, jonpas approved these changes

2019-08-05 23:21 UTC, jonpas requested changes

2019-08-05 23:21 UTC, jonpas commented on addons/sys_sem70/radio/fnc_initializeRadio.sqf
> +HASH_SET(_radioData,"volumeKnobPosition", EGVAR(sys_core,defaultRadioVolume)*5);
```suggestion
HASH_SET(_radioData,"volumeKnobPosition",EGVAR(sys_core,defaultRadioVolume) * 5);
```

2019-08-05 23:59 UTC, jonpas requested changes

2019-08-05 23:59 UTC, jonpas commented on addons/sys_sem52sl/radio/fnc_initializeRadio.sqf
> +HASH_SET(_radioData,"volumeKnobPosition", _volume / .125);
```suggestion
HASH_SET(_radioData,"volumeKnobPosition", _volume / 0.125);
```

2019-08-05 23:59 UTC, jonpas commented on addons/sys_sem52sl/radio/fnc_initializeRadio.sqf
> +_volume = _volume + .125 - (_volume % .125);
```suggestion
_volume = _volume + 0.125 - (_volume % 0.125);
```

2019-08-06 00:00 UTC, jonpas commented
Works well.

2019-08-06 09:15 UTC, jonpas approved these changes

2019-08-06 09:16 UTC, merged