API - setRadioData & getRadioData
IDI-Systems/acre2 pull request #835
Opened 2019-09-17 00:21 UTC by synixebrett

**When merged this pull request will:**
- Add `acre_api_fnc_getRadioData`
- Add `acre_api_fnc_setRadioData`

2019-09-17 02:22 UTC, jonpas requested changes

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_getRadioData.sqf
> + * Get the internal state of a radio
```suggestion
 * Get the internal state / serialized data of a radio.
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_setRadioData.sqf
> + * Set the internal state of a radio
```suggestion
 * Set the internal state / de-serialize data of a radio.
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_setRadioData.sqf
> + * 1: Radio Data <ARRAY>
```suggestion
 * 1: Radio Data (Serialized) <ARRAY>
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_setRadioData.sqf
> +    HASH_SET(EGVAR(sys_data,radioData), _radioId, _radioData call EFUNC(sys_data,deserialize));
```suggestion
    _radioData = _radioDataSerialized call EFUNC(sys_data,deserialize);
    HASH_SET(EGVAR(sys_data,radioData),_radioId,_radioData);
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_getRadioData.sqf
> +private _radioData = HASH_GET(EGVAR(sys_data,radioData), _radioId) call EFUNC(sys_data,serialize);
```suggestion
private _radioDataSerialized = HASH_GET(EGVAR(sys_data,radioData),_radioId) call EFUNC(sys_data,serialize);
```
Better play safe with macros and spaces.

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_setRadioData.sqf
> +_data params ["_radioType", "_radioData"];
```suggestion
_data params ["_radioType", "_radioDataSerialized"];
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_getRadioData.sqf
> +[_baseRadio, _radioData]
```suggestion
[_baseRadio, _radioDataSerialized]
```

2019-09-17 02:22 UTC, jonpas commented on addons/api/fnc_getRadioData.sqf
> + * Internal Radio Data <ARRAY>
```suggestion
 * Serialized Radio Data <ARRAY>
```

2019-09-17 12:23 UTC, Sniperhid commented
setRadioData is potentially a source of synchronisation issues between clients. The key is to mention that it has to be called globally - otherwise radio details will not be in sync. e.g. radio frequencies for one client may be out causing all sorts of issues. Please update the header to make this clear! (Might even be worth logging it's use should issues begin to appear!)

2019-09-18 00:50 UTC, synixebrett commented
What if we just made the effects global to prevent that issue?

2019-09-18 07:31 UTC, Sniperhid commented
> What if we just made the effects global to prevent that issue?

Most API methods in ACRE2 tend to have local effects so for consistency sake the local effect is useful.

2019-09-18 09:36 UTC, synixebrett commented
In this case though would it not be more useful to be global? Since it would be required anyway?

I could add a `_global` param that is true by default so you can set it to default if you do want local only effect for some reason

2019-10-01 05:51 UTC, TheMagnetar requested changes

2019-10-02 07:15 UTC, TheMagnetar approved these changes

2019-10-02 07:42 UTC, Sniperhid reviewed
I was thinking a bit about this and locality. The global parameter is a good idea, but something more important dawned on me.

Simple overriding the data doesn't quite feel right - This technically allows it to override radio data at any moment even. ACRE has an extensive system for synchronising data and processing events for setting channel data through `sys_data` which houses a fair bit of the code.

I think opting to use events (it would probably require a new event) that sets the data is a better one. It would even allow the interface of the radio to update should the user have the device open/is broadcasting etc.

The major downside to the event approach is there is more code. I think there's two approaches either use the existing events and send a lot of them  - I believe one would be required for each property inside the data as the current internal setData event sets one key/value at a time. The alternative would be to make a new event to set the entire radio data. The event system would also then handle the global transmission of data.

2020-05-19 16:11 UTC, Thymo- commented
Having a function to save and load radio states will allow radio's to be persisted between play sessions on long campaigns.

2021-02-24 15:42 UTC, jonpas commented
This should be changed to use data events as @Sniperhid got "dawned on".

2023-09-14 00:37 UTC, jonpas commented
No further activity, would have to be re-done with data framework.

2023-09-14 00:37 UTC, closed without merging