Update chinese translation
IDI-Systems/acre2 pull request #863
Opened 2019-11-15 03:10 UTC by TWRoach

Update Chinese

2019-11-15 08:10 UTC, TheMagnetar approved these changes

2019-11-15 08:11 UTC, TheMagnetar commented
Solve please the conflicts so that we can merge it

2019-11-16 00:18 UTC, TWRoach commented
Sorry, I am a newbie. What should I do?

2019-11-16 00:18 UTC, TWRoach commented
> Solve please the conflicts so that we can merge it

Sorry, I am a newbie. What should I do?

2019-11-17 01:52 UTC, TWRoach commented
> Solve please the conflicts so that we can merge it

yup i'm Stupid but I think I have solved it.

2019-11-20 21:11 UTC, TheMagnetar commented
Not really, there are duplicated translations, specially in German.

2019-11-20 21:12 UTC, TheMagnetar requested changes
For example, these are duplicated (more on that file). If you have trouble with GIT conflicts, i would suggest closing this PR and starting anew directly from the ACRE2 master branch :)

2019-11-20 21:12 UTC, TheMagnetar commented on addons/sys_rack/stringtable.xml
> +            <German>Funkgeräteschrank</German>
Duplicated translation

2019-11-24 09:34 UTC, TheMagnetar commented
You are still adding duplicated entries. In sys_rack module there is
`<German>Funkgeräteschrank</German>` and `<German>Anlage</German>` for key `<Key ID="STR_ACRE_sys_rack_Racks">`

2020-01-17 13:24 UTC, jonpas commented
@TWRoach please take another look at this PR. Looks like you were editing an older version. I tried to fix the conflicts.

2020-01-17 17:49 UTC, TheMagnetar approved these changes

2020-03-17 12:56 UTC, merged