Respawn - Fix MenuPosition with Spectator
IDI-Systems/acre2 pull request #929
Opened 2020-04-17 17:08 UTC by Superxpdude

**When merged this pull request will:**
- Prevent players from automatically being switched to ACRE Spectator if the `MenuPosition` *and* `Spectator` respawn templates are in use. This prevents dead players from being switched in and out of ACRE spectator while remaining dead. Fixes issue #916.

2020-04-17 20:09 UTC, jonpas requested changes
I like this implementation.

And this seems to make sense to me.

2020-04-17 20:09 UTC, jonpas commented on addons/sys_core/fnc_spectatorEGDisplayLoad.sqf
> +if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) AND !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```suggestion
if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```

2020-04-17 20:09 UTC, jonpas commented on addons/sys_core/fnc_spectatorEGDisplayLoad.sqf
> +};
```suggestion
};

```

2020-04-17 20:09 UTC, jonpas commented on addons/sys_core/fnc_spectatorEGDisplayUnload.sqf
> +if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) AND !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```suggestion
if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```

2020-04-17 20:09 UTC, jonpas commented on addons/sys_core/fnc_spectatorEGDisplayUnload.sqf
> +};
```suggestion
};

```

2020-04-26 05:38 UTC, Soldia1138 commented
Looking good, provided those to variables are set correctly by the game each and every time.

2020-04-26 06:38 UTC, mharis001 commented on addons/sys_core/fnc_spectatorEGDisplayLoad.sqf
> +if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```suggestion
if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && {!(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])}) then {
```

2020-04-26 06:38 UTC, mharis001 commented on addons/sys_core/fnc_spectatorEGDisplayUnload.sqf
> +if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && !(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])) then {
```suggestion
if (!(missionNamespace getVariable ["BIS_RscRespawnControlsMap_shown", false]) && {!(missionNamespace getVariable ["BIS_RscRespawnControlsSpectate_shown", false])}) then {
```

2020-05-02 19:25 UTC, jonpas approved these changes

2020-05-02 19:28 UTC, jonpas approved these changes

2020-05-02 19:28 UTC, merged