sys_gsa - Fix PFEH not being removed under some conditions
IDI-Systems/acre2 pull request #949
Opened 2020-05-03 20:00 UTC by PabstMirror

- GSA object deleted - PFEH now passes radioID to disconnect, so we can still remove the pfeh
- Radio removed by script - sys_radio,getRadioObject will return nil

also fix mast item being lost if no room in inventory

2020-05-03 20:16 UTC, jonpas requested changes
Nice!

2020-05-03 20:16 UTC, jonpas commented on addons/sys_gsa/fnc_disconnectServer.sqf
> + * 2: RadioID <STRING><OPTIONAL>
```suggestion
 * 2: RadioID <STRING> (default: "")
```

2020-05-03 20:16 UTC, jonpas commented on addons/sys_gsa/fnc_disconnectServer.sqf
> +if (_radioId == "") then { _radioId = _gsa getVariable [QGVAR(connectedRadio), ""]; };
```suggestion
if (_radioId == "") then {
    _radioId = _gsa getVariable [QGVAR(connectedRadio), ""];
};
```

2020-05-05 00:27 UTC, jonpas approved these changes

2020-05-05 05:54 UTC, TheMagnetar requested changes

2020-05-05 05:54 UTC, TheMagnetar commented on addons/sys_gsa/fnc_disconnectServer.sqf
> +    ERROR_3("Empty unique radio ID %1:%2:%3",_gsa,_unit,_radioId);
_radioId is empty, no need to log it.

```suggestion
    ERROR_2("Empty unique radio ID %1:%2",_gsa,_unit);
```

2020-05-19 09:57 UTC, TheMagnetar approved these changes

2020-05-21 21:56 UTC, merged