Cba setting gear desync
IDI-Systems/acre2 pull request #96
Opened 2016-11-13 07:58 UTC by Soldia1138

**When merged this pull request will:**
- Allow the player to disable the GearDesync Hint
- Most communities are aware of the issues with gearDesyncs
- Some players want to capture videos and don't care about gear desync
- If hint is disabled, it is written to rpt. So we can still debug it on upcoming issues

2016-11-13 12:11 UTC, jonpas requested changes

2016-11-13 12:11 UTC, jonpas commented on addons/sys_core/initSettings.sqf
> +    QGVAR(disableGearDesync),
I'd keep that as `QGVAR(disableDesyncHint)`, don't want people thinking it could in any way disable actual desync.

2016-11-13 12:11 UTC, jonpas commented on addons/sys_radio/fnc_monitorRadios.sqf
> +            diag_log _message;
As said on Slack, this should always be printed to RPT, even if it's hinted. And also using a macro. So this entire thing would become:
```
WARNING(_message);
if (!GVAR(disableDesyncHint)) then {
    hintSilent _message;
};
```

2016-11-13 12:12 UTC, jonpas commented
I honestly thing we should just get rid of the hint entirely. Logging it to RPT is enough, as it's not something we should worry about if nothing actually goes wrong.

2016-11-17 10:50 UTC, Sniperhid commented
IIRC, when this occurs new radios will no longer be initialised? This typically effects JIP/respawns but in the case of a one-life mission where everyone is spawned at the beginning this isn't a big deal. I might be wrong as I only encountered this once in the last 18 months.

2016-11-26 19:16 UTC, jonpas approved these changes

2016-11-26 22:08 UTC, Sniperhid approved these changes
I am willing to accept this as a temporary solution.

2016-11-27 18:22 UTC, merged