Extensions - Parse Startup Parameters Config File
IDI-Systems/acre2 pull request #961
Opened 2020-05-20 20:20 UTC by Thymo-

**When merged this pull request will:**
- Parse parameters from a [startup parameter file](https://community.bistudio.com/wiki/Startup_Parameters_Config_File#Pre_build_86060)
- Ignore old style parameter files which are broken on dedicated servers anyway
- Make it easier to parse command line arguments in the future (argv style)

2020-05-20 20:25 UTC, Thymo- commented
@Sniperhid Can you review this since you wrote the plugin copying code?

2020-05-21 06:38 UTC, TheMagnetar requested changes
just some minor comment

2020-05-21 06:38 UTC, TheMagnetar commented on extensions/src/ACRE2Steam/CallExt_DllMain.cpp
> +    std::string par_opt("-par=");
```suggestion
    const std::string par_opt("-par=");
```

2020-05-21 07:18 UTC, Sniperhid commented
Functionally looks okay, I shall defer to @TheMagnetar

2020-05-22 05:22 UTC, TheMagnetar approved these changes

2020-05-22 05:37 UTC, merged