God mode
IDI-Systems/acre2 pull request #999
Opened 2020-08-01 05:45 UTC by TheMagnetar

**When merged this pull request will:**
- Adds the God Mode feature.

God Mode allows  sending voice messages without attenuation effects to any player or group of players. The PR functionality includes:
- Integration with Chat Channel. All units matching the Chat Channel criteria will be sent a voice message once the additional PTT is pressed.
- Possibility to define up to 3  group presets that can be activated by additional PTTs.
- Possibility to send text messages to the group presets.
- A set of API  functions to configure the access to God Mode as well as setting  up the group presets.

2020-08-02 20:48 UTC, ThymoNL requested changes

2020-08-02 20:48 UTC, Thymo- commented on addons/sys_godmode/XEH_postInit.sqf
> +        ERROR_1("Tryied to add an already speaking God....",_speakingUnit);
Tried

2020-08-04 19:47 UTC, jonpas approved these changes

2020-08-04 20:08 UTC, merged

2020-08-05 04:31 UTC, PabstMirror commented on addons/sys_godmode/fnc_sendText.sqf
> +if !([GODMODE_GROUP1] call FUNC(accessAllowed)) exitWith { false };
Should this be using `_group` instead?

2020-08-05 08:07 UTC, jonpas commented on addons/sys_godmode/fnc_sendText.sqf
> +if !([GODMODE_GROUP1] call FUNC(accessAllowed)) exitWith { false };
It should.

2020-08-05 10:41 UTC, jonpas commented on addons/sys_godmode/fnc_sendText.sqf
> +if !([GODMODE_GROUP1] call FUNC(accessAllowed)) exitWith { false };
#1001